CXXFLAGS=-ggdb -Wall -std=c++11
CXX=g++


.PHONY: clean tidy

erikParent: erikParent.cpp
    $(CXX) $(CXXFLAGS) erikParent.cpp -o erikParent

erikChild: erikChild.cpp
    $(CXX) $(CXXFLAGS) erikChild.cpp -o erikChild